name: small data Journalism
markdown: kramdown
pygments: true
relative_permalinks: true
permalink: pretty
assets:
  js_compressor:  uglifier
  css_compressor: sass

references_file: references.csv

# Twitter
twitter_user: dancow
twitter_tweet_button: true
code_dir: 'downloads/code'

github_repo: dannguyen/smalldata_journalism